### ISSUE TITLE
Falscher interner Link

### ISSUE THREAD

**Issue by polarpixel** [factorylabs/rex_markitup#1]
Beispiel:
```
Ein Testlink 
```

Wenn ich das Wort "Testlink" mit der Home-Seite verlinke, kommt das hier raus:
```
Ein redaxo://1:HomeTestlink
```

Korrekt wäre aber (also dahinter und ohne Artikelname):
```
Ein Testlink:redaxo://1
```

**Comment by phoebusryan** [comment]
Angepasst in Version 1.0.6

**Comment by polarpixel** [comment]
Ist noch nicht ganz korrekt.
Das obige Beispiel ergibt nun bei mir:
```
Ein Home:redaxo://1Testlink
````
Korrekt wäre:
````
Ein "Testlink":redaxo://1
```

Sprich: "Home" als Artikelname muss da nicht rein, dafür muss der verlinkte Begriff vorn stehen. Und die Anführungszeichen um den Linktext fehlen noch. Man könnte natürlich überlegen, ob man ihn als Title-Tag einsetzt, die SEOs stehen ja auf sowas.
Dann wäre die Syntax so:
````
"Ein Testlink(Home)":redaxo://1
```

**Comment by phoebusryan** [comment]
So, ich hatte endlich Zeit mir das nochmals anzuschauen. Kannst du es nochmal prüfen?

Version 1.1.3 wird dafür benötigt.

**Comment by polarpixel** [comment]
Stimmt fast ;-)

Bei mir ergibt das dann das hier:
Ein "Home(Testlink)":redaxo://1

Müsste aber so sein:
Ein "Testlink(Home)":redaxo://1

**Comment by olien** [comment]
Ich erhalte

"Artikelname()":redaxo://12

Was soll in den () stehen?

**Comment by tbaddade** [comment]
> Was soll in den () stehen?

Der Artikelname

**Comment by olien** [comment]
Ah. Danke

**Comment by phoebusryan** [comment]
Genau. Vor der Klammer steht der Linktext und darin der Artikelname (für SEO-Menschen). Ich habe das wohl vertauscht, werd es aber in Kürze korrigieren.
