### ISSUE TITLE
Mehrfaches "insertProfile" verhindern

### ISSUE THREAD

**Issue by olien** [factorylabs/rex_markitup#12]
Wenn ich 'insertProfile' im Modulinput benutze wird jedesmal wenn ich das Modul aufrufe ein Profil angelegt.

Wie kann ich das verhindern?

**Comment by phoebusryan** [comment]
Mit einer abfrage drum herum ;)

Was möchtest du denn genau damit tun?

**Comment by olien** [comment]
Wie wäre die Abfrage?

naja. Ich habe das 'insertProfile' im Modul Input. Sofern ich jetzt das Mosul aufrufe wird das Profil angelegt. Und wieder und wieder und wieder. Halt bei jedem Aufrufen des Modulinputs (Editieren / Hinzufügen).

Wäre es nicht einfache im Addon zu prüfen ob es ein Profil gleichen Namens schon gibt und dann das Anlegen zu verhindern?

**Comment by phoebusryan** [comment]
Ich habe gerade die API erweitert, sodass dies möglich ist. Das Update folgt in Kürze.

if (!rex_markitup::profileExists('simple')) {
  rex_markitup::insertProfile('simple', 'Lorem Ipsum', 'textile', 'bold,italic');
}

**Comment by olien** [comment]
cool. danke!

**Comment by phoebusryan** [comment]
Version 1.1.2 ist nun draussen.
