### ISSUE TITLE
full Profile :: SyntaxError: Unexpected EOF (anonyme Funktion)markitup_profiles.js:22

### ISSUE THREAD

**Issue by tbaddade** [factorylabs/rex_markitup#15]
siehe Screenshot
![screenshot 2016-01-05 12 57 05](https://cloud.githubusercontent.com/assets/338267/12114657/e1514dc0-b3ab-11e5-8162-8b49f84b946b.png)

**Comment by phoebusryan** [comment]
Fixed in version 1.1.6.1
