### ISSUE TITLE
Listen ohne neue Zeile

### ISSUE THREAD

**Issue by polarpixel** [factorylabs/rex_markitup#2]
**Wenn ich keinen text markiert habe:**

Nach Klick auf den ol- oder ul-Button wird ein Zeilenumbruch erzeugt.
Besser wäre es, wenn nur Listenzeichen und Leerzeichen erzeugt wird, kein Enter.

**Wenn ich mehrere Zeilen markiert habe:**

Diese Zeilen werden korrekt mit Listenzeichen versehen. Danach wird aber noch eine neue Zeile erzeugt mit einem weiteren Listenzeichen und eine neue Leerzeile. Das erste sollte keinesfalls sein, das zweite müsste auch nicht sein, denke ich.

**Comment by phoebusryan** [comment]
Gefixt in Version 1.0.6, bitte bestätigen

**Comment by polarpixel** [comment]
Klappt bestens, danke!
Ich schließe gleich.
