### ISSUE TITLE
Vorschlag für die Optik

### ISSUE THREAD

**Issue by polarpixel** [factorylabs/rex_markitup#4]
Ich denke, dass es der Übersichtlichkeit dient, wenn sich die Iconleiste und besonders die Dropdowns ein klein wenig vom Textfenster abheben würden. Das "verschwimmt" sonst etwas.
Vielleicht ein helles dezentes Grau und für das Dropdown die Rahmenfarbe etwas dunkler oder ein dezentes box-shadow?

![2015-12-04_11-03-48](https://cloud.githubusercontent.com/assets/330160/11587025/0611c1f6-9a77-11e5-9027-a4359f87d813.png)

Vielleicht sähe ja auch eine dunkelgrauer Hintergrund mit hellen Icons nett aus?

![2015-12-04_11-11-55](https://cloud.githubusercontent.com/assets/330160/11587164/dccb1f58-9a77-11e5-8087-474b3e5bfdc5.png)

**Comment by phoebusryan** [comment]
Uh, das dunkle gefällt mir tatsächlich ganz gut. Warum eigentlich nicht. Gibt es dazu noch andere Meinungen? Auf jeden Fall würde ich dann den Style auch für den Redactor übernehmen.

**Comment by Sioweb** [comment]
Dunkel ist gut.

**Comment by olien** [comment]
once you go black you'll never go back

**Comment by phoebusryan** [comment]
Fixed in Version 1.0.7

**Comment by polarpixel** [comment]
Optisch gefällt mir das gut.
Die Farbe der Icons könnte aus meiner Sicht allerdings noch etwas heller sein.
Ich würde als Farbe fast weiß nehmen, dann bei Hover reines Weiß statt dem jetzigen Blauton.

Aber das ist vermutlich Geschmacksache, da ist meine Meine Meinung vermutlich nicht maßgeblich.

**Comment by phoebusryan** [comment]
Grundsätzlich gebe ich dir recht. ABER: Ich habe 1:1 die Farben der linken Spalte von R5 genommen. Das gleiche blau, grau, dunkelgrau etc. damit der Editor möglichst schön ins Backend passt. Gilt das als Argument?

**Comment by polarpixel** [comment]
Natürlich, dann hast Du vollkommen recht. Darauf hatte ich nicht geachtet.
Ich sehe schon, das ist dann eher eine Aufgabe für ein eigenes Theme – was wir beide ja auch schon im Kopf haben ...
