### ISSUE TITLE
formatting als eigene Buttons

### ISSUE THREAD

**Issue by tbaddade** [factorylabs/rex_markitup#6]
siehe https://github.com/factorylabs/rex_redactor/issues/18

**Comment by phoebusryan** [comment]
Closed bis es hier weiter geht: https://github.com/factorylabs/rex_redactor/issues/18

**Comment by tbaddade** [comment]
Aus factorylabs/rex_redactor#18
> Das Formatting ist fest in redactor verankert.

Trifft das auch hier zu?

**Comment by phoebusryan** [comment]
Nein, tut es nicht. Aber ich möchte die beiden Editoren so ähnlich haben wie möglich, damit es einfach wartbarer ist. Sprich; das Ergebnis aus dem Redactor-Issue (https://github.com/factorylabs/rex_redactor/issues/18) werde ich auch beim MarkItUp Umsetzen

**Comment by phoebusryan** [comment]
Gefixt in Version 1.1.4
