### ISSUE TITLE
textarea initial höher und bei längeren Text automatisch anpassen

### ISSUE THREAD

**Issue by tbaddade** [factorylabs/rex_markitup#7]
Bis jetzt bleibt textarea auf den initialen Werte von 2 rows des Browser. Passt sich auch nicht an, wenn längerer Text geschrieben wird.

**Comment by phoebusryan** [comment]
Das ist richtig; diesen habe ich (noch) nicht angepasst. Ich warte auf die definitive Lösung des Redactors.

**Comment by phoebusryan** [comment]
Gefixt in Version 1.2.0
