### ISSUE TITLE
Prüfen ob Textile Class vorhanden ist

### ISSUE THREAD

**Issue by tbaddade** [factorylabs/rex_markitup#8]
Nicht ob das AddOn vorhanden ist sondern die Class.

**Comment by phoebusryan** [comment]
Warum? Ich prüfe nicht mal ob Textile vorhanden ist. Schlussendlich kann man mit dem Editor einfach Textile und später noch Markdown zusammenklicken. Parsen tut es mein AddOn nicht. Der Gedanke ist aber, sobald möglich folgende Klasse einzusetzen: https://github.com/redaxo/redaxo/pull/248
